extends:
  - gplane
  - gplane/vue

rules:
  import/no-unresolved: 0
  import/no-extraneous-dependencies: 0

overrides:
  - files: '*.ts'
    parserOptions:
      parser: '@typescript-eslint/parser'
    rules:
      no-undef: 0
